<?php
define('DB_SERVER', 'CSDM-WEBDEV');
define('DB_USERNAME', '1813617');
define('DB_PASSWORD', '1813617');
define('DB_DATABASE', 'db1813617_cmm007');

$db =mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD, DB_DATABASE);

//FOR ANOTHER FILE
//CREATE A QGL QUERY AS A STRING